config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  devise_for :users

  resource :job, only: [:new, :create, :edit, :update]
  resources :worked_days, only: [:create]

  get 'dashboard' => 'dashboard#index'
  get 'report' => 'reports#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  has_many :worked_days

  def week_day_numbers
    [1, 2, 3, 4, 5]
  end

  def hours_per_day
    hours_per_week / week_day_numbers.count
  end

  def hours_this_week
    worked_days.this_week.pluck(:hours).sum
  end

  def hours_left_this_week
    [hours_per_week - hours_this_week, 0].max
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_one :job

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def job?
    job.present?
  end
end

app/models/worked_day.rb
class WorkedDay < ApplicationRecord
  belongs_to :job

  validates :hours, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 24 }

  scope :this_week, -> { where(date: Date.today.beginning_of_week..Date.today) }

  def week_day
    date.strftime('%a')
  end

  def today?
    date == Date.current
  end

  def today_css_class
    "today" if today?
  end
end

app/models/worked_week.rb
class WorkedWeek
  attr_reader :job, :range

  def initialize(job:, date: Date.today)
    @job = job
    @range = date.beginning_of_week..date.end_of_week
  end

  def worked_days
    worked_days = job.worked_days.where(date: range)
    worked_dates.map do |date| # add empty days
      worked_days.find { |day| day.date == date } || WorkedDay.new(date: date, hours: 0)
    end
  end

  private

  def worked_dates
    job.week_day_numbers.map do |week_day_number|
      range.to_a[week_day_number - 1]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def require_job
    authenticate_user!
    redirect_to new_job_path, notice: 'To continue you need to have a job.' unless current_user.job?
  end

  def require_job_absence
    authenticate_user!
    redirect_to dashboard_path, alert: 'You already have a job!.' if current_user.job?
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :require_job

  def index
    @worked_days_this_week = WorkedWeek.new(job: current_user.job).worked_days
    @worked_day = WorkedDay.new(hours: current_user.job.hours_per_day.to_i, date: Date.today)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if user_signed_in?
      return redirect_to new_job_path unless current_user.job?
      return redirect_to dashboard_path
    end
  end

  # this is for devise to work on the homepage
  helper_method :resource_name, :resource_class, :resource, :devise_mapping

  def resource_name
    :user
  end

  def resource_class
     User
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :require_job, only: [:edit, :update]
  before_action :require_job_absence, only: [:new, :create]
  before_action :set_job, only: [:edit, :update]

  def new
    @job = Job.new
  end

  def create
    @job = current_user.build_job(job_params)
    if @job.save
      redirect_to root_path, notice: 'Job successfuly created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @job.update(job_params)
      redirect_to dashboard_path, notice: "Job updated successfuly"
    else
      render :edit
    end
  end

  private

  def set_job
    @job = current_user.job
  end

  def job_params
    params.require(:job).permit(:hours_per_week)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    sundays = Date.today.downto(current_user.job.created_at.to_date).select(&:sunday?)
    @weeks = sundays.map { |sunday| WorkedWeek.new(job: current_user.job, date: sunday) }
  end
end

app/controllers/worked_days_controller.rb
class WorkedDaysController < ApplicationController
  before_action :require_job

  def create
    @worked_day = current_user.job.worked_days.build(worked_day_params)
    if @worked_day.save
      redirect_to dashboard_path, notice: 'Saved'
    else
      render 'dashboard/index'
    end
  end

  private

  def worked_day_params
    params.require(:worked_day).permit(:hours, :date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/dashboard/index.html.slim
.dashboard
  h1.hours-left = "#{current_user.job.hours_left_this_week} hours left this week"

  .this-week
    - @worked_days_this_week.each do |worked_day|
      .day class=worked_day.today_css_class
        .week-day = worked_day.week_day
        .worked-hours = worked_day.hours


  .worked-day-form = render 'worked_days/form'

app/views/home/index.html.slim
.welcome-page
  .welcome-text
    h1 Working Hours Tracker
    p A way to track how many hours have you worked this week
    p It is designed for people who don't have determined working schedule

  hr

  .authentication
    .signup
      h3 Register
      = render 'devise/registrations/form'
    hr
    .signin
      h3 Sign in
      = render 'devise/sessions/form'

app/views/jobs/edit.html.slim
.edit-job
  | How many hours per week do you work?
  = simple_form_for @job do |f|
    = f.input :hours_per_week
    = f.submit 'Save'

app/views/jobs/new.html.slim
.new-job
  | How many hours per week do you work?
  = simple_form_for(@job, url: job_path) do |f|
    = f.input :hours_per_week
    = f.submit 'Continue'

app/views/layouts/application.html.slim
doctype html
html
  head
    title Working Hours Tracker
    meta name="viewport" content="width=device-width, initial-scale=1"
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      .brand Working hours tracker
      nav
        .nav-left
          = link_to 'Dashboard', dashboard_path
          = link_to 'Report', report_path
        .nav-right
          - if user_signed_in?
            = link_to 'Sign out', destroy_user_session_path, method: :delete
    .notifications
      - flash.each do |key, value|
        div class="alert alert-#{key}"
          = value
          a.close[href="#" data-dismiss="alert"] ×
    main
      = yield

app/views/reports/index.html.slim
.report
  h1 Report
  .weeks
    - @weeks.each do |week|
      .date-range = "#{week.range.first} - #{week.range.last}"
      - week.worked_days.each do |worked_day|
        .week-day = "#{worked_day.week_day}: #{worked_day.hours} "
      hr

app/views/worked_days/_form.html.slim
= simple_form_for(@worked_day) do |f|
  h1 Log worked day
  .form-inputs
    = f.input :hours
    = f.input :date
  .form-actions
    = f.button :submit, "Save"